# This is list of essential configurations
DOT_CONFIGS=(
	fcitx5
	fish
	hypr
	kitty
	mcphub
	nvim
	opencode
	rofi
	uwsm
	vesktop
	wallpapers
	wayle
	yazi
)

SYSTEM_SERVICES=(
	tailscaled
	systemd-timesyncd
	bluetooth
	avahi-daemon
)

USER_SERVICES=(
	hyprpaper
	hyprsunset
	hypridle
	hyprpolkitagent
	wayle
	cliphist
)
