BOOTLOADER_UTILS=(
	grub
	efibootmgr
	dosfstools
	mtools
	fuse3
	os-prober
	sbctl
	ntfs-3g
	btrfs-progs
)

SYSTEM_UTILS=(
	wmctrl
	wl-clipboard
	cliphist
	awww
	brightnessctl
	power-profiles-daemon
	unzip
	fastfetch
	htop
	fish
	dust
	ripgrep
	fzf
	fd
	jq
	poppler
)

GNOME_UTILS=(
	dconf-editor
	gnome-tweaks
	extension-manager
)

HYPRLAND_UTILS=(
	# uwsm
	# libnewt
	hyprland
	hyprpaper
	hyprlock
	hypridle
	xdg-desktop-portal-hyprland
	xdg-desktop-portal-gtk
	hyprsunset
	hyprpolkitagent
	ags-hyprpanel-git
	hyprshot

	rofi
	rofi-emoji
	wtype
	qt5-wayland
	qt6-wayland
)

DEV_TOOLS=(
	visual-studio-code-bin
	neovim
	tree-sitter-cli
	python
	uv
	clang
	nodejs
	npm
	go
	golangci-lint
	rustup
	github-cli
	tailscale
	typst
	qemu-base
)

AI_TOOLS=(
	opencode
	antigravity-cli
)

INPUT_METHOD=(
	fcitx5
	fcitx5-configtool
	fcitx5-unikey
	fcitx5-gtk
	fcitx5-qt
)

COMMON_APPS=(
	vesktop
	firefox
	libreoffice-fresh
	mpv
	yazi
	trash-cli
	ffmpegthumbnailer
	kitty
	imagemagick
	nwg-look
	selectdefaultapplication-git
)

FONTS=(
	noto-fonts
	noto-fonts-cjk
	noto-fonts-emoji
	ttf-jetbrains-mono-nerd
	ttf-ms-win11-auto
)

THEMES=(
	catppuccin-gtk-theme-mocha
)
